---
name: Linda
surname: Cabrera Orellana
position: "Data Scientist"
address: "Granada, España"
phone: +34 624 609 588
www: lindajzmin-website.netlify.app/
email: "lindateachtech@gmail.com"
github: lindateachtech
linkedin: lindateachtech
date: "`r format(Sys.time(), '%B %Y')`"
output:
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Educación

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Universidad de Granada", "2024", "Máster en Técnicas Cuantitativas para la gestión empresarial", "Granada, España",
  "Universidad Politécnica de Valencia & Universidad de Valencia", "2018", "Master en Investigación Matemática", "Valencia, España",
  "Escuela Superior Politécnica del Litoral", "2014", "Ingeniera en Auditoría", "Guayaquil, Ecuador"
) %>%
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year,
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```
